# Generated by Django 5.2.5 on 2025-09-02 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emitente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='emitentes/')),
            ],
        ),
        migrations.AlterModelOptions(
            name='transacao',
            options={'ordering': ['-data']},
        ),
        migrations.RenameField(
            model_name='pagador',
            old_name='imagem',
            new_name='logo',
        ),
        migrations.AlterField(
            model_name='transacao',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.categoria'),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='data',
            field=models.DateField(),
        ),
        migrations.AddField(
            model_name='transacao',
            name='emitente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.emitente'),
        ),
    ]
