# Generated by Django 5.2.5 on 2025-09-02 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_emitente_alter_transacao_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transacao',
            options={},
        ),
        migrations.RemoveField(
            model_name='transacao',
            name='emitente',
        ),
        migrations.AlterField(
            model_name='emitente',
            name='nome',
            field=models.CharField(default='Minha Empresa', max_length=100),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='categoria',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.categoria'),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='pagador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.pagador'),
        ),
    ]
