# Generated by Django 5.2.5 on 2025-09-03 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_transacao_options_remove_transacao_emitente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoComprobatório',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='comprovantes/')),
                ('data_envio', models.DateField(auto_now_add=True)),
                ('transacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='core.transacao')),
            ],
        ),
    ]
