# Generated by Django 5.2.5 on 2025-09-04 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_instituicao_unidadepagadora_contapagar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contapagar',
            name='unidade_pagadora',
            field=models.CharField(max_length=100),
        ),
    ]
