# Generated by Django 5.2.5 on 2025-09-04 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_contapagar_unidade_pagadora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contapagar',
            name='instituicao',
            field=models.CharField(max_length=100),
        ),
    ]
